### ISSUE TITLE
cannot open shared object file

### ISSUE THREAD

**Issue by cinderblockgames** [eebette/Jellyfin-Tools#5]
I'm getting an error when trying to use `jellyfin-cover`:

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/jellyfin-cover", line 5, in <module>
    from cli.cli import main
  File "/home/ubuntu/.local/lib/python3.10/site-packages/cli/cli.py", line 6, in <module>
    from cli.image import create_library_image
  File "/home/ubuntu/.local/lib/python3.10/site-packages/cli/image.py", line 7, in <module>
    import cv2
  File "/home/ubuntu/.local/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

The call I'm making looks like this:

```
jellyfin-cover create --image image-name.jpg --title 'Library Title'
```

**Comment by eebette** [comment]
Try installing `opencv-python-headless`, I've read that this will install necessary dependencies that may be missing in some installations.

```sh
pip install opencv-python-headless
```
