### ISSUE TITLE
ModuleNotFoundError (Windows 11)

### ISSUE THREAD

**Issue by freetimehooligan** [eebette/Jellyfin-Tools#9]
Trying to run on Windows 11 install.

```
 C:\Users\wtbja>jellyfin-cover create --image C:\Users\wtbja\Downloads\wallpaperflare.com_wallpaper.jpg --title Halloween

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\wtbja\AppData\Roaming\Python\Python313\Scripts\jellyfin-cover.exe\__main__.py", line 4, in <module>
    from cli.cli import main
  File "C:\Users\wtbja\AppData\Roaming\Python\Python313\site-packages\cli\cli.py", line 8, in <module>
    from install import fix_install
  File "C:\Users\wtbja\AppData\Roaming\Python\Python313\site-packages\install\fix_install.py", line 14, in <module>
    from typing.io import IO
ModuleNotFoundError: No module named 'typing.io'; 'typing' is not a package

C:\Users\wtbja>
```

**Comment by eebette** [comment]
This is a result of outdated dependencies/incompatibility with Python 3.13. This is fixed in the latest release 1.0.2. 

`pip install --upgrade jellyfin-tools`

Thank you for using the tool!
